### ISSUE TITLE
Traefik URL rewriting is not working.

### ISSUE THREAD

**Issue by nitinkhandelwal26** [mspnp/aks-secure-baseline#107]
Hello Team,

When implementing Traefik URL rewriting in workload deployment:
https://github.com/mspnp/aks-secure-baseline/blob/main/workload/aspnetapp.yaml

```
    kubernetes.io/ingress.class: traefik-internal
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.options: default
    traefik.ingress.kubernetes.io/router.middlewares: app-gateway-snet@file, gzip-compress@file
    traefik.ingress.kubernetes.io/rewrite-target: / 
spec:
  # ingressClassName: "traefik-internal"
  tls:
  - hosts:
      - services-00.abc.com
        # In this Implementation we use a
        # wildcard default certificate added at Ingress Controller configuration level which is *.example.com
        # secretName: <services-00-example-com-tls-secret>
  rules:
  - host: services-00.abc.com
    http:
      paths:
      - path: /login
```

my workload which is having /login path at service, it's not working. can you please help...
